### ISSUE TITLE
Where are the arrows being generated?

### ISSUE THREAD

**Issue by jzadra** [socib/Leaflet.TimeDimension#217]
I'm curious where in the code the arrows are created.  I can't seem to find anything that specifies how they are drawn.

**Comment by r1m** [comment]
They are rendered with CSS using [Bootstrap Glyphicons](https://github.com/socib/Leaflet.TimeDimension/blob/master/src/leaflet.timedimension.control.css#L2)

```css
.timecontrol-play.pause:before {
    content: "\e073";
}
```
